### ISSUE TITLE
does upgrading armor work on FTB?

### ISSUE THREAD

**Issue by LightningAC** [chbachman/ModularArmour#66]
Hey, i am playing on Ftb horizons 2 daybreaker and i am playing on a server and everytime i try upgrading the armor i get dc-ed and then the resources i used for in gets eaten by it. so i lose the resources everytime.
Any fix for this?

**Comment by ChromeFlux** [comment]
im playing on this modpack too, what version are you on? 1.0.2?

**Comment by HowardRoark2016** [comment]
I have some "armor upgrading" weirdness with ModularArmor on FtB Horizons: Daybreaker 1.0.2.

I believe Daybreak 1.0.2's default version of ModularArmor is "ModularArmour-1.7.10-1.0.13-36". I removed it and installed "ModularArmour-1.7.10-1.0.17-40". I could not test that version because FtB crashed before my world would launch (I will try that version again, however). I removed it and installed "ModularArmour-1.7.10-1.0.15-38". The same weirdness I experienced with 13-36 was still present in 15-38. I tried all of the following with both versions:

I crafted three of the four armor items just fine (I did not attempt to craft the chestplate). I held the leggings in my hand and right-clicked. The GUI appeared. I then proceeded to craft a Reinforced Energy item. The recipe calls for tempered ingots in the four corners. However, once I click on one of the boxes in the top row of the crafting grid, the HardcoreEnderExpansion GUI would appear. I tapped on the ESC key to back out and noticed that my tempered ingot was missing from my inventory. I exited my inventory and then re-opened my inventory. My tempered ingot was back. I tried changing EnderExpansion's key to something else. Still, ModularArmor's GUI made the EnderExpansion GUI appear. So, I took hold of the boots and right-clicked. No GUI appeared but the booted immediately disappeared. I grabbed my helmet and right-clicked. Same issue as the leggings with the top row of the crafting grid. I exited back to my inventory. I happened to click the empty box where my boots were previously. The moment I did, the boots re-appeared. 

Just thought I'd mention my findings here for future readers. No doubt this will all be sorted in a future version. To that end, I am off to try the most recent two versions of ModularArmor starting with "ModularArmour-1.7.10-1.0.17-40". If all goes well, I will return with good news.

**Comment by HowardRoark2016** [comment]
Well, I installed "ModularArmour-1.7.10-1.0.17-40" and my world launched just fine this time. I grabbed the Modular Leggings and right-clicked. Crash. I started up FtB and my world again. Right-clicked the leggings. Crash. 

Crash log is here - http://pastebin.com/2TT5hxuk

**Comment by chbachman** [comment]
@LightningAC If I could get a log I could help you out. 

@HowardRoark2016 Crash Log doesn't even mention me at all. (Not saying it doesn't it is just really weird.)

**Comment by LightningAC** [comment]
well it doesn't crash my game, it just kicks me from the server. and in the log it just says "disconnected from server" when you normally disconnect.

**Comment by chbachman** [comment]
Could I just get the entire log?

**Comment by HowardRoark2016** [comment]
@chbachman Were they RF leggings?
 
The leggings at issue are called "Modular Leggings". The world "Modular" proceeds all the armor at issue in my post (with the exception of the chestplate as I had never crafted that item). The Modular Armor appears with a black texture and is that which is crafted with "tempered electrum". 

@chbachman Was this with a new pair of leggings? Did the leggings have any Upgrades?

I'm sorry. I should have explained things better for you and future readers. I am using Windows 7 Ultimate x64-bit SP1 and Java 8 update 11 (build 1.8.0_11-b12) while playing MC 1.7.10 SSP via FtB Horizons: Daybreaker v1.0.2 in a Realistic World Gen Alpha-generated world with 4.5GB of RAM allocated to FtB. They were freshly created Modular Leggings with no upgrades. I am unable to craft the upgrades because it is while using the Upgrade Crafting GUI that I experience the problem with older versions of ModularArmour. I am unable to craft upgrades because of this problem. I mean for the following to be a literal play-by-play of my actions: I crafted three Modular Armor items (leggings, helmet, and boots). I held the leggings in my hand and right-clicked. The leggings GUI appeared. I then proceeded to craft a Reinforced Energy item. I could scroll through all the upgrade items just fine. I could place items in the lower row of the GUI's crafting grid. However, I could not click into the upper row of the crafting grid without issue. When I click in that row, the GUI for HardcoreEnderExpansion would appear. Upon exited out of that GUI, the item I held while clicking on that upper row of the crafting grid had disappeared from my hand only to re-appear in my inventory several moments later. 

The issue I mentioned in the paragraph above occurred with both the 13-36 and 15-38 versions of ModularArmour with no crashes. However, with 16-39 and with 17-40, Minecraft would crash the moment I right-clicked a held Modular Leggings or Modular Helmet (I did not try with the boots or the chestplate). By the way, I tried all of the above with both Optifine installed and not installed only to experience the same results. At this moment I have 17-40 installed and running and I am about to right-click on the Modular Leggings once again to produce a new crashlog which I shall post. 

Crashlog:
http://pastebin.com/aBWtE49b

**Comment by chbachman** [comment]
Update CoFH Core to 3.0.3

**Comment by LightningAC** [comment]
log: http://paste.feed-the-beast.com/view/2f342a2f
and how do i update mods in a modpack?

**Comment by LightningAC** [comment]
also what does CoFH core stand for?

**Comment by chbachman** [comment]
CoFH Core = Base mod for Thermal Expansion, I tap into it as well.

CoFH = Cult of the Full Hub (IDK why, ask lemming)

**Comment by LightningAC** [comment]
so how do you update the individual mods?

**Comment by LightningAC** [comment]
nvm i got it

**Comment by LightningAC** [comment]
since i updated cofh core to 3.0.3 1) it will not let me on a server 2)i played on a single player and it crashed
also i could not get a crashlog for some reason

**Comment by HowardRoark2016** [comment]
@LightningAC @chbachman 

I am playing with FtB Horizons: Daybreak v1.02. I had an issue with Modular Armour (read above). The default 1.02 version of this modpack uses CoFHCore [1.7.10] 3.0.2-262. I did as chbachman said and upgraded to CoFHCore [1.7.10] 3.0.3-303 just a moment ago.

("Upgrading" means that I downloaded the 3.0.3-303 version, then I used Windows Explorer and went to the "\ftb\FTBHorizonsII\minecraft\mods" folder, then I deleted the "CoFHCore-[1.7.10]3.0.2-262.jar" file I found there, then I copy/pasted the "CoFHCore-[1.7.10]3.0.3-303.jar" file into the "mods" folder.)

I am happy (overjoyed! ecstatic! blissful! euphoric! jubilant!) to report that I was able to right-click my Modular Leggings (with no crash) and I was able to click into those upper three boxes of its crafting grid (without Hardcore Ender Expansion's GUI popping) and crafted myself a Leadstone Energy upgrade! 

I downloaded CoFHCore [1.7.10] 3.0.3-303 from this link - 
http://minecraft.curseforge.com/mc-mods/69162-cofhcore/files
